version: '3.5'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /app
        container_name: practica-php
        restart: unless-stopped
        volumes:
            - ./:/app
        ports:
            - "${APP_PORT}:8080"
        networks:
            - practica-php

    mysql:
        image: "mysql:latest"
        container_name: mysql-database-practica
        command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
        restart: unless-stopped
        ports:
            - "${DB_PORT}:3306"
        tty: true
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        networks:
            - practica-php

    phpmyadmin:
        image: "phpmyadmin:latest"
        container_name: phpmyadmin-practica
        depends_on:
            - mysql
        environment:
            - PMA_HOST=${PMA_HOST}
        ports:
            - '${PMA_PORT}:80'
        networks:
            - practica-php

networks:
    practica-php:
      external:
        name: personal-network
